package com.zplus.tataskymsales.databse.table

import io.realm.RealmObject
import io.realm.annotations.PrimaryKey

open class RechargeRequest (
    @PrimaryKey open var _ID : Int = 0,
    open var request_datetime : String = "",
    open var hash_id : String = "",
    open var recharge_txn_code : String = "",
    open var operator_type_code : String = "",
    open var operator_type : String = "",
    open var recharge_type : String = "",
    open var recharge_type_code : String  = "",
    open var gateway_slug : String = "",
    open var from_sim_lapu_no : String = "",
    open var to_sim_lapu_no : String = "",
    open var amount : String = "",
    open var category_name : String = "",
    open var sub_category_name : String = "",
    open var sub_category_code : String = "",
    open var rechargetype_code : String = "",
    open var from_sim_pin_no : String = "",
    open var usertype : String = "",
    open var is_frc : String = "",
    open var salutation : String = "",
    open var name : String = "",
    open var last_name : String = "",
    open var date_of_birth : String = "",
    open var address_1 : String = "",
    open var address_2 : String = "",
    open var alt_mob_no : String = "",
    open var landmark : String = "",
    open var pincode : String = "",
    open var city : String = "",
    open var state : String = "",
    open var box_no : String = "",
    open var vc_no : String = "",
    open var product_frc_id : String = "",
    open var sbttype : String = "",
    open var stbcategory : String = "",
    open var av_pin : String = "",
    open var uuid : String = "",
    open var circle : String = "",
    open var token : String = "",
    open var package_price : String = "",
    open var request_type : String = "",
    open var to_lapu_id : String = "",
    open var from_lapu_id : String = "",
    open var apptype : String = "",
    open var otp : String = "",
    open var entityid : String = "",
    open var entityloginid : String = "",
    open var entityloginpassword : String = "",
    open var entityeprs : String = "",
    open var role : String = "",
    open var recharge_token_id : String = "",
    open var enckey : String = "",
    open var ivspec : String = "",
    open var id : String = ""
) : RealmObject()